### ISSUE TITLE
Do we need this website?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/documentation-theme-jekyll#9]
This repository is publishing a website from the `gh-pages` branch. 

https://ioos.github.io/documentation-theme-jekyll/

Do we need that website? I don't see it linked anywhere on our documentation portal and it's missing the top navigation menu (see screenshot below).  

If we want to keep serving this page, we should update [_config.yml](https://github.com/ioos/documentation-theme-jekyll/blob/gh-pages/_config.yml) to point to the appropriate places.

- [ ] Edit github_editme_path. (`Edit me` links don't point to the right place)
- [ ] change top_nav to topnav_ioos

![image](https://user-images.githubusercontent.com/8480023/221577965-9eeba1c8-573d-41a4-b29a-21f2f2cb157e.png)

**Comment by mwengren** [comment]
No, I think we can wipe it out.  We should consolidate any documentation related to our own ioos.github.io pages or Jekyll site framework in https://github.com/ioos/ioos-documentation-jekyll-skeleton instead.  This is just a duplicate of the source Jekyll theme anyway.

We could add more instructions/pages in addition to https://ioos.github.io/ioos-documentation-jekyll-skeleton/howto.html if it made sense to do that.

**Comment by MathewBiddle** [comment]
Okay, I'll nuke the `gh-pages` branch and remove the Pages piece.

**Comment by MathewBiddle** [comment]
Done https://ioos.github.io/documentation-theme-jekyll/
